# Generated by Django 3.1.1 on 2021-02-20 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0005_auto_20210220_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='microenterpreneur',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='fk_address',
        ),
    ]
