# Generated by Django 3.1.1 on 2021-02-20 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0006_auto_20210220_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.customer'),
        ),
        migrations.AddField(
            model_name='microenterpreneuraddress',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.microenterpreneur'),
        ),
        migrations.AddField(
            model_name='storeaddress',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store'),
        ),
        migrations.AddField(
            model_name='warehouseaddress',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.warehouse'),
        ),
    ]
