# Generated by Django 3.1.1 on 2021-02-20 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0007_auto_20210220_2127'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address_line1', models.TextField()),
                ('address_line2', models.TextField()),
                ('pincode', models.IntegerField()),
                ('geolocation', models.CharField(max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.city')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.state')),
            ],
        ),
        migrations.RemoveField(
            model_name='microenterpreneuraddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='microenterpreneuraddress',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='microenterpreneuraddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='storeaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='storeaddress',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='storeaddress',
            name='state',
        ),
        migrations.RemoveField(
            model_name='warehouseaddress',
            name='city',
        ),
        migrations.RemoveField(
            model_name='warehouseaddress',
            name='fk_address',
        ),
        migrations.RemoveField(
            model_name='warehouseaddress',
            name='state',
        ),
        migrations.DeleteModel(
            name='CustomerAddress',
        ),
        migrations.DeleteModel(
            name='MicroenterpreneurAddress',
        ),
        migrations.DeleteModel(
            name='StoreAddress',
        ),
        migrations.DeleteModel(
            name='WarehouseAddress',
        ),
        migrations.AddField(
            model_name='customer',
            name='fk_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AddField(
            model_name='microenterpreneur',
            name='fk_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AddField(
            model_name='store',
            name='fk_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='fk_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
    ]
