# Generated by Django 3.1.1 on 2021-02-21 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0008_auto_20210220_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='storecheckout',
            name='fk_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product'),
        ),
    ]
