# Generated by Django 3.1.1 on 2021-02-24 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0011_customer_fk_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AlterField(
            model_name='microenterpreneur',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AlterField(
            model_name='store',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='fk_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.address'),
        ),
    ]
