# Generated by Django 3.1.1 on 2021-02-26 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0016_auto_20210226_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Microenterpreneur',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoApp.address')),
                ('microenterpreneur_name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=1)),
                ('mobile', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
            bases=('djangoApp.address',),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_code', models.IntegerField()),
                ('fk_microenterpreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.microenterpreneur')),
            ],
        ),
    ]
