# Generated by Django 3.1.1 on 2021-02-26 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0017_microenterpreneur_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Store',
        ),
    ]
