# Generated by Django 3.1.1 on 2021-02-26 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0018_delete_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_number', models.TextField(max_length=50)),
                ('sales_invoice_number', models.TextField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('address_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangoApp.address')),
                ('store_name', models.CharField(max_length=100)),
                ('store_code', models.IntegerField()),
                ('fk_microenterpreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.microenterpreneur')),
            ],
            bases=('djangoApp.address',),
        ),
        migrations.CreateModel(
            name='StoreCheckout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('invoice_number', models.CharField(max_length=100)),
                ('is_delivery', models.BooleanField()),
                ('is_online', models.BooleanField()),
                ('promotions', models.CharField(blank=True, max_length=100, null=True)),
                ('cast_discount', models.FloatField()),
                ('sub_total', models.FloatField()),
                ('grand_total', models.FloatField()),
                ('payments', models.FloatField(blank=True, null=True)),
                ('loyalty_point_used', models.IntegerField(blank=True, null=True)),
                ('wallet_amount_used', models.FloatField(blank=True, null=True)),
                ('fk_customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.customer')),
                ('fk_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreInventoryTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('mrp', models.FloatField()),
                ('expiry_date', models.DateField()),
                ('batch_number', models.IntegerField()),
                ('txn_type', models.CharField(choices=[('stock_transfer', 'stock_transfer'), ('stock_return', 'stock_return'), ('local_purchase', 'local_purchase'), ('stock_audit_adjustment', 'stock_audit_adjustment'), ('pos_returns', 'pos_returns')], max_length=100)),
                ('reference_number', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('comment', models.CharField(max_length=100)),
                ('fk_barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.productbarcode')),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='StoreInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.FloatField(default=False)),
                ('quantity', models.IntegerField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('fk_product', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StoreCheckOutItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField()),
                ('mrp', models.FloatField()),
                ('sp', models.CharField(max_length=100)),
                ('attributed_cart_discount', models.FloatField()),
                ('fk_product', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_store_checkout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.storecheckout')),
            ],
        ),
        migrations.CreateModel(
            name='StoreAssortment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=1)),
                ('min_qty', models.IntegerField(blank=True, null=True)),
                ('max_qty', models.IntegerField(blank=True, null=True)),
                ('sp', models.IntegerField(blank=True, null=True)),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store')),
            ],
        ),
        migrations.CreateModel(
            name='StocktransferItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrp', models.FloatField()),
                ('expiry_date', models.DateTimeField(auto_now_add=True)),
                ('quantity', models.IntegerField()),
                ('fk_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.product')),
                ('fk_stock_transfer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangoApp.stocktransfer')),
            ],
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='fk_store',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='djangoApp.store'),
        ),
    ]
