# Generated by Django 3.1.1 on 2021-02-26 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0019_auto_20210226_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecheckout',
            name='fk_product',
        ),
    ]
