# Generated by Django 3.1.1 on 2021-03-03 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0020_remove_storecheckout_fk_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='geolocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
