# Generated by Django 3.1.1 on 2021-03-03 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0021_auto_20210303_1247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='fk_manufacturer',
        ),
        migrations.AddField(
            model_name='category',
            name='fk_parent_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
