# Generated by Django 3.1.1 on 2021-03-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoApp', '0022_auto_20210303_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image_link',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
